export default {
  title: 'Section',
  name: 'pageSection',
  type: 'reference',
  to: [
    {type: 'Header'},
    {type: 'hero'},
    {type: 'Cases'},
    {type: 'Counters'},
    {type: 'TextHero'},
    {type: 'Services'},
    {type: 'Technologies'},
    {type: 'Review'},
    {type: 'Code'},
    {type: 'Footer'},
    {type: 'AboutHero'},
    {type: 'Roadmap'},
    {type: 'OurMission'},
    {type: 'Careers'},
    {type: 'Jobs'},
    {type: 'Benefits'},
  ],
}
