export default {
  title: 'Section',
  name: 'pageSection',
  type: 'reference',
  to: [
    {type: 'Header'},
    {type: 'hero'},
    {type: 'Cases'},
    {type: 'Counters'},
    {type: 'CasesPage'},
    {type: 'TextHero'},
    {type: 'Dignity'},
    {type: 'Services'},
    {type: 'Technologies'},
    {type: 'Review'},
    {type: 'Code'},
    {type: 'Footer'},
    {type: 'AboutHero'},
    {type: 'Roadmap'},
    {type: 'OurMission'},
    {type: 'Careers'},
    {type: 'Jobs'},
    {type: 'Benefits'},
    {type: 'ServiceHero'},
    {type: 'Offer'},
    {type: 'Digital'},
    {type: 'Expect'},
    {type: 'JobHero'},
    {type: 'JobText'},
    {type: 'OurServices'},
    {type: 'ProjectHero'},
    {type: 'ProjectTextImage'},
    {type: 'ProjectText'},
    {type: 'ProjectImages'},
    {type: 'ProjectGallery'},
  ],
}
